name: DatabaseRequest
description: A request form for data operational and maintenance requests (e.g., load, delete, and reload data) into the SDR Shared environment.
title: "[DatabaseRequest]:"
labels: ["dataSupport"]
assignees:
  - sdr-support
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a DatabaseRequest!
  - type: dropdown
    id: type
    attributes:
      label: Environment
      description: Which environment are you requesting access for?
      options:
        - Sandbox
        - Demo
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description 
      description: Description or reference to Request.
      placeholder: Please provide description
    validations:
      required: true
