name: Incident
description: An issue that is causing downtime to the SDR environment for single or multiple users connecting to the system.
title: "[Incident]: "
labels: ["incident"]
assignees:
  - sdr-support
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Incident!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Environment
      description: Which environment are you raising incident for?
      options:
        - Sandbox
        - Demo
    validations:
      required: true
  - type: textarea
    id: defaulttag
    attributes:
      label: Mail Trigger
      description: Add any additional users who may want to be notified regarding this issue. 
      placeholder: Add any users to be notified e.g.@username.
    validations:
      required: false
 
