name: Incident
description: An issue that is causing downtime to the SDR environment for single or multiple users connecting to the system.
title: "[Incident]: "
labels: ["incident"]
assignees:
  - SushmitabSinha
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Incident!
  - type: input
    id: contactdetails
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Environment
      description: Which environment are you raising incident for?
      options:
        - Sandbox
    validations:
      required: true
  - type: textarea
    id: defaulttag
    attributes:
      label: Mail Trigger
      description: This will trigger a mail to Support Team. You can mention anyone with @username.
      placeholder: Notify the Support Team.
      value: "@Migration-Sample/sdr-support"
    validations:
      required: true
 
